
# -*- coding: utf-8 -*-
# Author        : Jesse Wei
# LastUpdate    : 2020/11/04
# Impact        : DAG generated by SQLG
# Message       : Humanity towards others, we live by sharing. Fear can hold you prisoner, only hope can set you free.

# from __future__ import print_function
import logging
import re
import airflow
from datetime import datetime, timedelta
from airflow.operators.sensors import ExternalTaskSensor
from airflow.operators.python_operator import PythonOperator
from airflow import models
from airflow.models import Variable
#from acme.operators.dwh_operators import PostgresOperatorWithTemplatedParams

# XSLT:loop: declaration: START{
import sqlg_jobs_PRD

data_stage = re.findall(r"_(.*?)_","D_ODS_PRD_SRC")

args = {
    "owner": "JESSEWEI",
    'start_date': airflow.utils.dates.days_ago(1),
    'provide_context': True
}	
# XSLT:loop: declaration: END}

ExternalTaskSensor.ui_color = 'white'
ExternalTaskSensor.ui_fgcolor = 'blue'

tmpl_search_path = Variable.get("sql_path")
	

# XSLT:loop: JOB_FLOW_NAME: START{
D_ODS_PRD_SRC = airflow.DAG(
    "D_ODS_PRD_SRC",
    tags=["PRD", data_stage[0]],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)
D_ODS_CUS = airflow.DAG(
    "D_ODS_CUS",
    tags=["PRD", data_stage[0]],
    schedule_interval="@daily",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)
M_ODS_CUS = airflow.DAG(
    "M_ODS_CUS",
    tags=["PRD", data_stage[0]],
    schedule_interval="@monthly",
    dagrun_timeout=timedelta(minutes=60),
    template_searchpath=tmpl_search_path,
    default_args=args,
    start_date=airflow.utils.dates.days_ago(1),    
    max_active_runs=1
	)

# XSLT:loop: JOB_FLOW_NAME: END}

# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: External:START{{

my_taskid = "D_ODS_PRD_SRCxD_STG_INIT__SYS_STS_STG"
D_ODS_PRD_SRCxD_STG_INIT__SYS_STS_STG= ExternalTaskSensor(
#    schedule_interval=None,
    pool = "sensor_pool",
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    mode="reschedule",
    dag=D_ODS_PRD_SRC,
#    execution_delta=None,  # Same day as today
)

my_taskid = "D_ODS_CUSxD_STG_INIT__SYS_STS_STG"
D_ODS_CUSxD_STG_INIT__SYS_STS_STG= ExternalTaskSensor(
#    schedule_interval=None,
    pool = "sensor_pool",
    task_id=my_taskid,
    external_dag_id="D_STG_INIT",
    external_task_id="SYS_STS_STG",
    mode="reschedule",
    dag=D_ODS_CUS,
#    execution_delta=None,  # Same day as today
)
	
# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: External: END}}


# XSLT:loop: JOB_FLOW_NAME: START{


# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: START{{

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B.dag=D_ODS_PRD_SRC
# DEBUG:D_STG_INIT::D_ODS_PRD_SRC
D_ODS_PRD_SRCxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: END}}


# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: START{{

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B.dag=D_ODS_PRD_SRC
# DEBUG:D_STG_INIT::D_ODS_PRD_SRC
D_ODS_PRD_SRCxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: END}}


# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: START{{

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B.dag=D_ODS_PRD_SRC
# DEBUG:D_STG_INIT::D_ODS_PRD_SRC
D_ODS_PRD_SRCxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.MTL_SYSTEM_ITEMS_B)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_WH.set_downstream(sqlg_jobs_PRD.UC_Group_Customer_Location_STG)
sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.UC_Group_Customer_Location_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Group_Customer_Location_LD)
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.dag=D_ODS_CUS
# DEBUG:D_STG_INIT::D_ODS_CUS
D_ODS_CUSxD_STG_INIT__SYS_STS_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH)
sqlg_jobs_PRD.UC_Project_Decision_Customer_STG.dag=D_ODS_CUS
# DEBUG:D_ODS_CUS::D_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Project_Decision_Customer_WH.set_downstream(sqlg_jobs_PRD.UC_Project_Decision_Customer_STG)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: START{{{
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.UC_Customer_Grouping_Map_STG.set_downstream(sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD)
sqlg_jobs_PRD.UC_Customer_Grouping_Map.dag=M_ODS_CUS
# DEBUG:M_ODS_CUS::M_ODS_CUS
sqlg_jobs_PRD.ODS_UC_Customer_Grouping_Map_LD.set_downstream(sqlg_jobs_PRD.UC_Customer_Grouping_Map)

# 		XSLT:loop: Rows-by-JOB_FLOW_NAME: JOB_NAME: END}}}

# 	XSLT:loop: JOB_FLOW_NAME-and-PRE_JOB: Dependency: END}}

# XSLT:loop: JOB_FLOW_NAME: END}


